# This is a basic workflow to help you get started with Actions

name: Change Malware Dep Status

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab sd
    workflow_dispatch:
        inputs:
            dep-name:
                description: "Dep. Name"
                required: true
                default: "octokit"
            dep-version:
                description: "Dep. Version"
                required: true
                default: "5.1.20"
            dep-status:
                type: choice
                description: New Status
                options:
                    - safe
                    - confirmed_by_xygeni
                    - confirmed_malware

env:
    XY_USERNAME: ${{ secrets.XY_USERNAME_DEMO }}
    XY_PASSWORD: ${{ secrets.XY_PASSWORD_DEMO }}
    XY_URL: ${{ secrets.XY_URL_DEMO }}
    XY_TOKEN: ${{ secrets.XY_TOKEN_DEMO }}
    XY_PRJ_NAME: GitHub-${{ github.event.repository.name }}
    PKG_NAME: ${{ github.event.inputs.dep-name }}
    PKG_VERSION: ${{ github.event.inputs.dep-version }}
    PKG_STATUS: ${{ github.event.inputs.dep-status }}
    DEF_LANGUAGE: "javascript"

jobs:
    # This workflow contains a single job called "xygeni_security_scan"
    change_status:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        steps:
            - name: Change Status
              run: |
                  curl --location --request POST $XY_URL/report/upload/malware/status \
                      --header "Authorization: Bearer $XY_TOKEN" \
                      --form "name=\"$PKG_NAME\"" \
                      --form "version=\"$PKG_VERSION\"" \
                      --form "language=\"$DEF_LANGUAGE\"" \
                      --form "status=\"$PKG_STATUS\""

                  mw="$PKG_NAME-$PKG_VERSION"
                  text="Changed $mw status to $PKG_STATUS !!! "
                  echo "::notice $mw::$text"
